### ISSUE TITLE
Add user management for organization

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#119]
Chaque structure doit pouvoir consulter et modifier le profil de ses users.

Une structure parent doit pouvoir le faire pour les users de ses enfants

**Comment by fmeynard** [comment]
WIP

Petites questions : 
- La structure est-elle modifiable ? ( je dirai oui, mais uniquement par les orga parentes ) 
- Date de naissance modifiable ? ( je dirai oui, mais ca change le "mot de passe" de lutilisateur )
- identification number  ? ( je dirai oui, mais ca change le "mot de passe" de lutilisateur )
-  email ? ( je dirai oui, mais ca change le "mot de passe" de lutilisateur )

**Comment by mRoca** [comment]
On fera un autre ticket pour la modification des structures.

Tout les champs des users doivent être modifiable,  en effet
