### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#132]
The priority is to test :

- [x] User register
- [x] User connection
- [x] User availabilities
- [x] Organization connection
- [ ] Organization planning filters
- [ ] Organization availability book

**Comment by matks** [comment]
Hi, what do you mean by functional tests ?
- integration behavior driven tests, like Behat tests ? testing scenarios (with real database, filled with fixtures)
- end-to-end browser driven tests, like puppeteer / selenium / panther tests ?

**Comment by mRoca** [comment]
For now, I think Behat or sf WebTestCase would be the easiest. If we really need to have some e2e browser tests, Panther should be enough.

**Comment by mRoca** [comment]
Closed in favor of many other tickets
