### ISSUE TITLE
Form improvements

### ISSUE THREAD

**Issue by hammat** [crf-devs/resop#138]
Quelques retours d'usages des formulaires.

Formulaire d'inscription :
- la case par défaut pour indiquer la vulnérabilité doit être sur "Je fais partie des personnes vulnérables". L'utilisateur doit donc faire une action pour la suite.
- Changer le label "Fonctions de cadre au sein de votre UL / DT" en "Fonction de cadre au sein de votre structure d'emploi"
- Ajouter "Solidar" dans la liste des compétences
- Fonctions CI : CI Réseau BSPP, CI Réseau Samu, CI
- Pouvoir laisser le métier vide
- Placer le bouton valider à droite
- Hint "Cochez toutes vos compétences" au dessus des réponses, sous le label du champ.

Formulaire des disponibilités : 
- Placer "Submit" à droite à la place de "Tout Sélectionner"
- Placer Tout sélectionner au dessus des disponibilités, à gauche.
- Changer "Submit" en "Enregistrer"
- Je sélectionne des disponibilités, je change de semaine, mes dispos sont perdues. Forcer la sauvegarde avant de pouvoir changer de semaine ou empêcher de changer de semaine si changement dans les disponibilités

Formulaire de recherche des disponibilités : 
- pouvoir afficher toutes les structures en un click
- n'afficher que l'heure de début du créneau pour alléger l'affichage (on aurait 00 02 04 06 au lieu de 00 02 02 04 04 06...)

Formulaire véhicule
- Identifiant au lieu de nom

**Comment by mRoca** [comment]
`Formulaire de recherche des disponibilités => pouvoir afficher toutes les structures en un click` c'est à dire ? En tant que DT, il existe un bouton "Afficher le planning de tous les bénévoles" sur la homepage
