### ISSUE TITLE
Availabilities view enhancements

### ISSUE THREAD

**Issue by hammat** [crf-devs/resop#141]
Quelques éléments pour faciliter l'usage de l'affichage : 

- Garder les jours et horaires en fixe lorsqu'on scroll bas dans les disponibités
- Avoir les dispos collées à gauche quand on ne sélectionne qu'un seul jour
- Ordre des compétences : CI bspp, ci samu, ci
- Afficher le nombre de personnes disponibles sur toute la journée : 
Mardi 24 mars       (12) |            Mercredi 25 mars       (7) |             Jeudi 26 mars

**Comment by mRoca** [comment]
Sticky headers are done in #157 
Skills order are done in ?

Afficher le nombre de personnes disponibles sur toute la journée => pas vraiment logique, étant donné que les gens ne seront pas dispo sur la ournée entière, si ?

**Comment by hammat** [comment]
On me dit que ça permet de visualiser rapidement le nombre de personnes dispo sur toute la journée. On a des bénévoles qui le sont bien oui. (un peu affiché comme la page dispo de pegass)

**Comment by mRoca** [comment]
Comme on peut clicker sur la colonne du jour pour trier par nombre de dispo sur la journée, ça fait pas le taf ? Le chiffre ne correspondrait pas à grand chose sans explication

**Comment by hammat** [comment]
Oui, ça raffiche le nombre par section. Ca évite de compter si beaucoup de ligne mais ok sinon !
