### ISSUE TITLE
Default vulnerability status

### ISSUE THREAD

**Issue by gcodeur** [crf-devs/resop#171]
Bonjour !

Lorsque l'on modifie les informations de son profil, le champ pour indiquer si l'on est vulnérable est mis à « oui » par défaut, peu importe sa valeur antérieure. Le problème est que l'on peut éditer son profil pour une toute autre raison et ne pas se rendre compte que l'on modifie aussi ce champ.

Si je ne me trompe pas, cela vient de cette ligne : https://github.com/crf-devs/resop/blob/629a2ca2e99e07ef4694574aec0a9fd3c64c7a5b/src/Form/Type/UserType.php#L87

Je suggère soit de prendre la valeur qui était initialement remplie, soit, si le but était que la personne vérifie à chaque fois cette info, de ne pas mettre de valeur par défaut afin que l'on doive explicitement cocher une case.

PS : bravo pour avoir codé tout ça en une semaine, c'est très quali ;)

**Comment by fmeynard** [comment]
Merci pour le feedback ! 

Jai fix ca du coup dans https://github.com/crf-devs/resop/pull/170
