### ISSUE TITLE
Vulnerabilities is not displayed correctly

### ISSUE THREAD

**Issue by hammat** [crf-devs/resop#176]
Je m'enregistre comme non vulnérable dans le formulaire. Quand je reviens sur le formulaire, la case cochée est celle qui m'indique comme vulnérable.

**Comment by mRoca** [comment]
@hammat peux-tu checker sur master ? Normalement c'est déjà corrigé

**Comment by fmeynard** [comment]
Duplicate of #171

**Comment by hammat** [comment]
Argh c'est plus réactif que moi ici, bien vu !
