### ISSUE TITLE
Explain in README what can be done to help

### ISSUE THREAD

**Issue by matks** [crf-devs/resop#180]
Hi, I just saw [this tweet](https://twitter.com/pixxelboy/status/1244227704582365184) and I'm willing to help. However I'm quite puzzled where to begin. I have no idea what the app does, what features are implemented (and need improvement), what features are yet to be done.

There is a list of open issues but they are mainly technical improvements (be responsive, use better birthday picker, add functional tests), not needed features.
Or maybe all features are already implemented 😄and all that's left is improvement

Would it be possible to write quick description of the app behavior and the missing items ?

The best would be to have
- issues and put them into a sorted Kanban board so we know we can just pick up the highest item in "todo" column
- provide a demo app instance (I assume https://resop.aws.mroca.fr/ is the production instance ?) with available credentials to see what's going on

But it's more work, I dont want to ask for too much

I hope this message does not sound rude 🙏

**Comment by mRoca** [comment]
You can have a look to #181 and join the chan ;-)
