### ISSUE TITLE
Allow filter on all structure in structure section

### ISSUE THREAD

**Issue by hammat** [crf-devs/resop#188]
En tant que structure parente dans le formulaire de recherche, je veux pouvoir afficher filtrer sur toutes les structures en un seul click
Alors toutes les structures seront sélectionnée d'un coup

**Comment by mRoca** [comment]
=> Dans la page planning
=> ajouter une croix à droite du sélecteur de structure pour tout désélectionner d'un coup ?

**Comment by fmeynard** [comment]
@hammat 

La lib qu'on utilise actuellement supporte : 
![selectAllActions](https://user-images.githubusercontent.com/469571/77968545-8140c300-72df-11ea-8ec0-8f4501d588a6.PNG)

Est-ce que ca t'irait ?

**Comment by hammat** [comment]
Parfait oui, merci !
