### ISSUE TITLE
Add planning colors meaning

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#193]
Il faudrait ajouter une légende pour expliquer les couleurs 
- du calendrier de sélection de dispo utilisateur / véhicule
- du planning global des structures

=> à voir comment présenter ça de façon discrète

**Comment by hammat** [comment]
+1, beaucoup demandé.

Pour rappel : 
Bleu : le bénévole ou véhicule est mobilisé sur une mission
Vert : le bénévole ou véhicule est indiqué disponible pour être mobilisé
Rouge : le bénévole ou véhicule est indiqué comme indisponible
Noir : le bénévole ou véhicule est indiqué comme en incapacité d'être mobilisé
