### ISSUE TITLE
Improve planning performances

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#204]
In production, with 500 users & 25000 availabilities, the fpm container renders the /planning page in more than 4 seconds.

Blackfire profile on my computer, with the same database : https://blackfire.io/profiles/9f06b56b-5f18-4b9c-83e8-c8d8d737f618/graph

**Comment by mRoca** [comment]
Second profile : https://blackfire.io/profiles/8dade8d8-4465-4d70-9da0-0dfb18c0be84/graph

Difference: https://blackfire.io/profiles/compare/286cfbba-a7d0-48e8-af34-54ac1119ac54/graph

**Comment by mRoca** [comment]
=> charger les premières colonnes en twig (nom/info des users et assets) et les dispo en ajax, ce serait peut-être le mieux

**Comment by mRoca** [comment]
=> ne pas hydrater les dates des disponibilités
=> faire le template planning en php et pas en twig
=> cache twig ?

**Comment by mRoca** [comment]
=> cache HTTP

**Comment by vincentchalamon** [comment]
À tester : https://github.com/twigphp/twig-cache-extension
