### ISSUE TITLE
Improve fixtures coherence

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#229]
Au chargement des fixtures, les disponibilités des bénévoles & véhicules sont complètement random. Ce n'est pas logique si on compare à la prod :

![image](https://user-images.githubusercontent.com/4746261/78501219-110cc400-775b-11ea-9e5c-8e6b4f10a653.png)

Il faudrait donc créer des fixtures plus cohérentes, avec:
- 30% des utilisateurs sans dispo
- 10% des utilisateurs interdit de mission (`locked`: case noire)
- 20% des utilisateurs tout le temps dispo
- 40% des utilisateurs parfois dispo (voir plus bas)

**Parfois dispo**
Les utilisateurs parfois dispo doivent l'être de façon cohérente: par exemple le WE et les soirs de 18h à minuit, ou seulement certains jours. Sur les plages dispo, il faudrait ajouter des créneaux réservés (voir plus bas).

**Dispo et réservé**
Sur les créneaux dispo, il faudrait avoir des plages `booked` (en bleu) d'entre 3 et 8 créneaux successifs.

Chaque utilisateur peut avoir une réservation tous les deux jours, par exemple.

**Comment by mRoca** [comment]
Autre exemple:

![image](https://user-images.githubusercontent.com/4746261/78501580-41a12d80-775c-11ea-8599-f655a3a0b253.png)

**Comment by Nick59** [comment]
Je regarde !

**Comment by Nick59** [comment]
Hello, 

Alors ce n'est pas parfait, mais c'est déjà mieux.

Qu'en pensez-vous ? 

![new-fixtures](https://user-images.githubusercontent.com/661550/78585726-a2069c80-783a-11ea-84a9-58966715b45e.png)

Question, dois-je faire la même  chose pour les véhicules ? Si oui, pouvez-vous me donner les pourcentages et differents cas aussi ?

**Comment by mRoca** [comment]
C'est déjà beaucoup mieux !

Pour les véhicules:
- 10% interdit de mission (`locked`: case noire)
- 30% sans dispo
- 30% toujours dispo, parfois réservé
- 30% parfois dispo, parfois réservé

**Dispo et réservé**
Sur les créneaux dispo, il faudrait avoir des plages booked (en bleu) d'entre 3 et 8 créneaux successifs.
