### ISSUE TITLE
Check why does the node.js install in CI take so long

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#243]
https://github.com/crf-devs/resop/pull/241/checks?check_run_id=564679647

https://github.com/crf-devs/resop/pull/241/checks?check_run_id=564679667

=>   Install Node.js === 3m 29s

It was 3s before : https://github.com/crf-devs/resop/runs/563802466?check_suite_focus=true

**Comment by fmeynard** [comment]
@mRoca i think its no longer a valid ticket
