### ISSUE TITLE
Add a help menu in the planning page 

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#268]
Il faudrait ajouter un bouton d'aide (`?`) dans la page planning pour expliquer quelques tips

- utiliser un browser à jour pour avoir la sticky bar
- clicker sur un jour dans le header du planing pour trier par dispo
- utiliser la touche MAJ pour une selection multiple

**Comment by maximepiard** [comment]
Je peux m'en occuper aujourd'hui.

Petite question sur la spec : Je part sur un bouton `Aide` entre la recherche et les résultats

![image](https://user-images.githubusercontent.com/13153190/79114548-d66ee100-7d83-11ea-9bc2-8a879663a83b.png)

Celui ci ouvre une  `modal` avec aucun CTA, mais une croix pour la quitter, et le texte ci dessous à l'intérieur.

---

- Utilisez un navigateur récent pour que l'entête suive lorsqu'on scrolle le long du tableau
- Cliquez sur un jour dans l'entête du tableau pour trier par disponibilités ce jour-ci
- Utiliser la touche MAJ entre deux clics pour sélectionner plusieurs cases

----

N'hésite pas si tu as des retours sur ces choix :point_up:

**Comment by mRoca** [comment]
Peut-être mettre le bouton d'aide en position absolue haut à droite de la page, histoire de ne pas augmenter la hauteur du header ? (à voir comment l'afficher sur smartphone)

Navigateur récent => on peut même conseiller Chrome ?
