### ISSUE TITLE
Add some fields into the Assets entity

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#277]
Dans le formulaire:
- ajout de l’immatriculation
- Ajout d'un champ textarea "Commentaires"

Dans le planning:
- Affichage de certaines informations au clic sur « plus d’informations »

**Comment by nikophil** [comment]
je prends ce ticket :)

**Comment by nikophil** [comment]
@mRoca possible d'expliciter le `Affichage de certaines informations au clic sur « plus d’informations »` stp ?

il va y avoir un problème avec le `thead` où il y a le nom des colonnes qui sont spécifiques aux bénévoles, non ? qu'est-ce que tu préconises ?

**Comment by mRoca** [comment]
Il faudrait faire deux thead avec le même nombre de colonnes, et un z-index plus grand pour le second. Comme les headers sont sticky, le second couvrira le premier.

**Comment by nikophil** [comment]
ok, bonne idée, après on n'a pas vraiment le droit de mettre plusieurs `thead` dans un tableau.

soit on part quand même là-dessus, mais pas sûr que ça soit bien x-browser (ça fonctionne sur ff et chrome)
sinon, je transforme ces `thead` en `tbody` qui ne contiendrait que des `th` ?

côté données, j'ai remanié le tableau `availabilities` pour d'en faire un tableau associatif avec deux entrées `assets` et `users`, afin que ça soit plus facile à traiter

**Comment by mRoca** [comment]
Chrome is enough ;-)
