### ISSUE TITLE
A parent organization must list and manage children assets

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#303]
=> Une structure parente doit pouvoir lister et modifier les véhicules de ses structures enfants
=> Ajouter un bouton "Véhicules" dans chaque ligne de la liste des structures enfants
=> Afficher tous les véhicules des enfants dans la liste des véhicules du parent, en ajouter la colonne "Structure"

**Comment by nikophil** [comment]
je me charge de ce ticket
