### ISSUE TITLE
Add a "search by all those skills" filter option in the planning

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#305]
=> dans les filtres du planning, il faut ajouter une case "Afficher uniquement les bénévoles ayant toutes les compétences cochées" à droite du sélecteur des compétences

**Comment by laurentChin** [comment]
Afficher les bénévoles ayant toutes les compétences cochées devrait être le comportement par défaut, l'affichage actuel des compétences et du planning (difficilement lisible quand affiché en même temps) donne très peu d'intérêt à une recherche sur l'une ou l'autre des compétences aujourd'hui nous ne faisons quasiment jamais de recherche sur plusieurs compétences étant donné ce fonctionnement.
