### ISSUE TITLE
Add a delete button in the mission types list

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#306]
=> enlever le bouton "supprimer" de la page d'édition des types de mission et le placer dans la liste, comme pour les véhicules
=> supprimer la protection csrf

**Comment by olivmai** [comment]
je prends ;)

**Comment by olivmai** [comment]
@mRoca  quelques remarques questions par rapport à cette issue.
Pour le bouton de suppression, on est d'accord qu'on veut le même comportement que sur la liste des véhicules par exemple (modal pour confirmation) ? Si oui au lieu de dupliquer du code avec les modal à chaque fois, est-ce qu'on utiliserait pas un plugin du genre https://sweetalert2.github.io/ (déjà utilisé sur d'autres projets, ça marche bien et c'est simple d'utilisation).
Egalement, sur le côté plus ergonomique, j'ai aussi vu des différences entre les deux pages (type de mission et véhicules), est-ce que j'en profite pour replacer le bouton d'ajout d'un nouveau type de mission comme pour les véhicules et avec le même style ? Et du coup aussi mettre le même style sur le bouton de modification et le tableau ?

**Comment by mRoca** [comment]
pour les popup, je pense qu'on peut faire très facilement la même chose que le plugin avec quelques lignes de jquery et des data-attr sur les boutons.

pour l'uniformisation des pages, pas de soucis !

**Comment by olivmai** [comment]
OK. alors je vais déjà voir pour faire un truc simple en reprenant ce qui est fait pour les véhicules et en harmonisant les styles des pages. Ca fera une PR plus rapide.
Je proposerais une autre PR à part avec une refacto pour éviter de dupliquer la modal à chaque fois qu'on en a besoin pour des confirmations.
