### ISSUE TITLE
See how to provide a nominative organization login

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#325]
Il faudrait permettre d'utiliser des comptes nominatifs pour les organizations, tout en gardant la possibilité de se connecter avec le mot de passe de la struture

Le besoin: savoir qui a fait quoi et quand

=> dans la liste des users d'une structure, permettre SI L'UTILISATEUR ACTUEL s'est identifié avec le mot de passe de la structure (= admin) d'indiquer cetains users comme étant administrateur de la structure
=> un user administrateur verra un bouton "Accéder à la gestion de la structure XXXX" dans sa page d'accueil utilisateur
=> au clic sur le bouton, l'utilisateur est connecté à l'espace structure (ajouter un rôle, ou utiliser IS_FULLY_AUTHENTICATED (?)
=> il faut pouvoir récupérer le user courant en plus de l'organization courante
=> dans le formulaire de login des structures, mettre un lien "Si vous êtes identifié comme administrateur de votre structure, connectez-vous à votre espace bénévole et accédez ensuite à l'espace d'administration", avec un lien vers la homepage bénévole

**Comment by nikophil** [comment]
closed in favor of #338
