### ISSUE TITLE
[Panther] Panther-extension for Behat

### ISSUE THREAD

**Issue by Guikingone** [crf-devs/resop#357]
**Describe the bug**
Hi everyone 👋 

Small update about a Slack discussion that I've started with @nikophil & @vincentchalamon, after looking at the behat process in a Symfony 5 app, it seems that the application env does not load correctly.

During this discussion, it seems that the Panther-extension does not receive the correct env, even when moving to `test` env in `Behat/Mink-Extension`, the panther client seems to call the `dev` one. 

**To Reproduce**
Boot a Symfony 5 projet then require:
- `behat`
- `friends-of-behat/symfony-extension`
- `friendsofbehat/mink-extension` 
- `guikingonepanther-extension`

**Expected behavior**
When launching the tests, a `print last response` must return the `dev` response (profiler included) rather than the `test` response.

**Solution**

After looking at the Symfony 5 bootstrap file: 

```php
<?php

use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

if (!class_exists(Dotenv::class)) {
    throw new LogicException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
}

// Load cached env vars if the .env.local.php file exists
// Run "composer dump-env prod" to create it (requires symfony/flex >=1.2)
if (is_array($env = @include dirname(__DIR__).'/.env.local.php') && (!isset($env['APP_ENV']) || ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV']) === $env['APP_ENV'])) {
    (new Dotenv(false))->populate($env);
} else {
    // load all the .env files
    (new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');
}

$_SERVER += $_ENV;
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? null) ?: 'dev';
$_SERVER['APP_DEBUG'] = $_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? 'prod' !== $_SERVER['APP_ENV'];
$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = (int) $_SERVER['APP_DEBUG'] || filter_var($_SERVER['APP_DEBUG'], FILTER_VALIDATE_BOOLEAN) ? '1' : '0';
```
And the one on this repository: 

```php
<?php

declare(strict_types=1);

use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

$testScripts = ['behat', 'phpunit'];
foreach($testScripts as $script) {
    if(false !== strpos($_SERVER['PHP_SELF'] ?? '', $script)) {
        $_SERVER['APP_ENV'] = 'test';
        break;
    }
}

// Load cached env vars if the .env.local.php file exists
// Run "composer dump-env prod" to create it (requires symfony/flex >=1.2)
if (is_array($env = @include dirname(__DIR__).'/.env.local.php') && ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV']) === $env['APP_ENV']) {
    foreach ($env as $k => $v) {
        $_ENV[$k] = $_ENV[$k] ?? (isset($_SERVER[$k]) && 0 !== strpos($k, 'HTTP_') ? $_SERVER[$k] : $v);
    }
} elseif (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
} else {
    // load all the .env files
    (new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');
}

$_SERVER += $_ENV;
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? null) ?: 'dev';
$_SERVER['APP_DEBUG'] = $_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? 'prod' !== $_SERVER['APP_ENV'];
$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = (int) $_SERVER['APP_DEBUG'] || filter_var($_SERVER['APP_DEBUG'], FILTER_VALIDATE_BOOLEAN) ? '1' : '0';
```

It seems that the `Env` component should be in charge of populating the env instead of looping through the env variables, I'm not completely sure about WHY the `Env` component should populate it (the `putEnv()` seems to be the pivot point here) but it seems the `test` env requires to create the `.env.local.php` instead of loading values from `.env` (which is the default behaviour), so, Symfony must load data from the `.env.local.php` file instead of using the `.env` one (which define the `dev` env in our case), the file can be generated from `composer dump-env test`. 

That's a strange behaviour but it seems that `(new Dotenv(false))->loadEnv(dirname(__DIR__).'/.env');` is the key problem here, it only load the `.env` file and don't override the env thanks to a `.env.test` file. 

Any feedbacks? 🙂

**Comment by mRoca** [comment]
I would be easier to discuss it in the vocal Discord channel, if you want ;-)

**Comment by mRoca** [comment]
The main thing here is as we are running everything in a docker container, the APP_ENV environment var is always set (dev or prod).

Regarding the env loop, I think it comes from a previous bootstrap file version, when the Dotenv was for always included in prod.

`it seems the test env requires to create the .env.local.php` => I don't understand this point, as we enter the first if only if this file exists AND its defined env is the same as the current one

` it only load the .env file and don't override the env thanks to a .env.test file.` => if you have a look to the `loadEnv()` function, you can see those lines:
```php
        if (file_exists($p = "$path.$env")) {
            $this->load($p);
        }

        if (file_exists($p = "$path.$env.local")) {
            $this->load($p);
        }
```

so, imo, the `.env.test` is well loaded if the APP_ENV var is well set

**Comment by Guikingone** [comment]
Hi @mRoca 👋 

Exactly, regarding the fact that you cannot override the `.env` file content, here's the process: 

- If a `.env` of `.env.dist` file exist, Sf will load it
- If a `APP_ENV` var is defined, Sf take this value and set it as the default value (in this case and by default, `dev`)

From here, Sf will act like that: 

- If there's a `.env.dev` file, Sf will use it to override env values

But, Sf will not load the `.env.test` as the env is set to `dev` in the same time, Sf will also look for a `.env.local.php` file (which can contain the `APP_ENV` value), so, here's my approach regarding the issue that we're facing: 

- Define the `.env` file and set all the values that you need. 
- Define a `.env.test` file which override values for the `test` env
- Define a `.env.local.php` file thanks to `composer dump-env test` ONLY before launching the Behat tests (PHPUnit don't need it) thanks to the Makefile: 

```Makefile
behat: ## Launch Behat features
behat: .env.test
    ## Other steps like database
    $(PHP) composer dump-env test
    $(PHP) vendor/bin/behat 
    rm -rf .env.local.php
```

This way, you can keep the `.env` file clean and define values only for the tests env. 

Any thoughts?

**Comment by Guikingone** [comment]
I've tried this approach on a clean project (Sf 5 version and with my extension installed), I've planned to test it tomorrow on this project 🙂

**Comment by Guikingone** [comment]
Hi everyone 👋 

So, I've just finish to test the app using the `dump-env test` command for the `test` env. 

Here's the process: 

- Change the `guikingone/panther-extension` to `^0.2.1` in `composer.json`
- Update the `Makefile`: 

```Makefile
test-behat:
	bin/tools composer dump-env test
	bin/tools sh -c "APP_DEBUG=1 APP_ENV=test bin/post-install-test.sh"
	- bin/tools vendor/bin/behat --format=progress
	rm -rf .env.local.php
```

- Use `make test-behat` (only with builded assets, maybe it could be a good idea to add something like that: 

```Makefile
test-behat: vendors webpack-build-dev ## or webpack-build-prod for faster steps?
	bin/tools composer dump-env test
	bin/tools sh -c "APP_DEBUG=1 APP_ENV=test bin/post-install-test.sh"
	- bin/tools vendor/bin/behat --format=progress
	rm -rf .env.local.php
```

The `test.log` is correctly generated: 

![var/log](https://i.postimg.cc/4xZQHtzS/Screenshot-2020-04-30-at-08-44-05.png)

And the tests are green: 

![Behat](https://i.postimg.cc/Hn6d0br9/Screenshot-2020-04-30-at-08-45-09.png)

For now, it's not clear why the `bin/tools` file does not set the `APP_ENV` for the `vendor/bin/behat` cmd.

**Comment by mRoca** [comment]
@Guikingone do you think you can join the Discord server? It'll be easier to discuss this point ;-) 

I think doing `composer dump-env test` is not the best way to fix the problem, but I need to be sure I understand your point

**Comment by Guikingone** [comment]
If everything is solved, I close this issue 🙂
