### ISSUE TITLE
Use dynamic config for user fields

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#388]
Les champs suivants ne sont pas communs à toutes les utilisations possibles de l'app et devraient donc être paramétrables:

- Vulnérable
- Quelles sont vos fonctions de cadre au sein de votre structure d'emploi ?
- Quelle est votre profession ?
- Avez-vous un uniforme en dotation chez vous ?
- Avez-vous le permis B depuis plus de 3 ans ?

**Comment by nikophil** [comment]
TODO :
- [ ] handle this change in planning filters
- [ ] data migration
