### ISSUE TITLE
User.phoneNumber does not accept 07...

### ISSUE THREAD

**Issue by vincentchalamon** [crf-devs/resop#411]

**Comment by mRoca** [comment]
It does work for all attributed phone numbers (you can test with `0783010101` for example).

CF https://fr.wikipedia.org/wiki/Liste_des_pr%C3%A9fixes_des_op%C3%A9rateurs_de_t%C3%A9l%C3%A9phonie_mobile_en_France

**Comment by mRoca** [comment]
=> there is no phone number between `06 99` and `07 50 00`

**Comment by vincentchalamon** [comment]
OK, I tried with 07 12..., that's why
