### ISSUE TITLE
Deal with already connected user in login pages

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#60]
Si je suis connecté en tant que user ou structure, je ne dois pas voir de formulaire de connexion mais : `vous êtes déjà connecté, clickez [ici pour retourner à votre espace personnel] ou [ici pour vous déconnecter]`

- /login
- /organization/login

**Comment by florianbelhomme** [comment]
Je n'ai pas suivi totalement la demande, je met les utilisateurs sur leur page d'accueil, le lien déco est toujours en haut à droite
