### ISSUE TITLE
Change the fully equiped form type

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#64]
`Avez-vous un uniforme en dotation chez vous ?` => Plutôt qu'une seule case à cocher , un radio oui/non, ou un select ou revoir la formulation

**Comment by ThibaultRoger** [comment]
Bonjour,

Je propose cette modification.
[Changethefullyequipedformtype#64.zip](https://github.com/crf-devs/resop/files/4371088/Changethefullyequipedformtype.64.zip)

Cordialement,
Thibault Roger

**Comment by florianbelhomme** [comment]
J'ai fait une PR avec les fichiers ci dessus

**Comment by mRoca** [comment]
Merci beaucoup @ThibaultRoger et @florianbelhomme !
