### ISSUE TITLE
Validate the Red Cross identification number format

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#66]
Format : `^\d+[A-Z]$`

**Comment by florianbelhomme** [comment]
C'est a quel endroit ? dans le login ?

**Comment by mRoca** [comment]
A la connexion on peut entrer soit son "nivol", soit sont adresse mail. une détection est faîte pour déterminer si c'est l'un ou l'autre en fonction de `filter_var($login, FILTER_VALIDATE_EMAIL)`.

Si c'est pas un email, c'est un NIVOL. 

Il faudrait valider ce fameux nivol dans le formulaire de création de compte (assert sur l'entité user ?) et afficher un message "Le numéro NIVOL saisi n'est pas valide" ou un truc du genre
